### ISSUE TITLE
使用tablayout时，XrecyclerView在切换tab时会崩溃。

### ISSUE THREAD

**Issue by xwzy** [XRecyclerView/XRecyclerView#290]
在使用tablayout的时候，多个tab下都有一个XrecyclerView，当一个XrecyclerView下拉刷新几次时，前往其他tab后，再返回该tab时，点击一个item，会报position的数组越界错误。

如果没有下拉过，切换tab时，也会发生错误。

是否是因为资源被系统自动回收了？还是XrecyclerView的问题？谢谢。

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test/com.example.test.QViewActivity}: java.lang.IndexOutOfBoundsException: Index: 26, Size: 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2713)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2774)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6272)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
Caused by: java.lang.IndexOutOfBoundsException: Index: 26, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.example.test.QViewActivity.onCreate(QuestionViewActivity.java:33)
	at android.app.Activity.performCreate(Activity.java:6864)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
	... 9 more

```

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{71cb804 position=19 id=-1, oldPos=-1, pLpos:-1 no parent}
at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5339)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5521)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1316)
at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1061)
at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1727)
at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2927)
at com.jcodecraeer.xrecyclerview.XRecyclerView.onTouchEvent(XRecyclerView.java:280)
at android.view.View.dispatchTouchEvent(View.java:10037)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2628)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:417)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
at android.app.Activity.dispatchTouchEvent(Activity.java:3198)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:379)
at android.view.View.dispatchPointerEvent(View.java:10266)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4514)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4379)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3912)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3965)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3931)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4058)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3939)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4115)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3912)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3965)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3931)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3939)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3912)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6323)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6297)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6258)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6448)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6397)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6471)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
at android.view.Choreographer.doCallbacks(Choreographer.java:688)
at android.view.Choreographer.doFrame(Choreographer.java:617)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
at android.os.Handler.handleCallback(Handler.java:754)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6272)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

```

**Comment by af913337456** [comment]
不是 xr 问题
