### ISSUE TITLE
往下滑动崩溃

### ISSUE THREAD

**Issue by zybooo1** [XRecyclerView/XRecyclerView#304]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.demo.demo, PID: 14413
                                                                              java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{3a4228e position=15 id=-1, oldPos=-1, pLpos:-1 no parent}
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                                                  at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                                  at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                                  at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                                  at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                                  at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                                  at android.os.Handler.handleCallback(Handler.java:754)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:160)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6207)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)

**Comment by zybooo1** [comment]
我用的是1.3.2版本 ，请问更新到1.4.2可以解决这个问题吗?

**Comment by af913337456** [comment]
考虑下个人代码逻辑原因。上述信息得不出相关点
