### ISSUE TITLE
刷新的时候，报错IllegalArgumentException

### ISSUE THREAD

**Issue by 4332weizi** [XRecyclerView/XRecyclerView#349]
版本：1.5.9
只有一条数据的时候，刷新报错。

```
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{c37e36e position=0 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)} com.jcodecraeer.xrecyclerview.XRecyclerView{2b8a0f VFED..... .F....ID 0,96-720,1132 #7f0900fe app:id/pick_up_recycler}, adapter:com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter@d348a9c, layout:android.support.v7.widget.LinearLayoutManager@242bca5, context:com.qk365.thweeks.MainActivity@34c85ce
                                                                       at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:842)
                                                                       at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
                                                                       at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1355)
                                                                       at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:4049)
                                                                       at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:555)
                                                                       at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:242)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3882)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
                                                                       at android.view.View.layout(View.java:19659)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
```

**Comment by 4332weizi** [comment]
测了一下，刷新删除第一条数据就崩溃

**Comment by 4332weizi** [comment]
RecyclerView删除数据并快速插入导致的， 数据改变后notify一次就好了
