### ISSUE TITLE
添加2个header就会导致报错

### ISSUE THREAD

**Issue by lileini** [XRecyclerView/XRecyclerView#354]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{9acda11 position=1 id=-1, oldPos=-1, pLpos:-1 no parent} com.loyo.library.view.xrecyclerview.LoyoRecyclerView{159b65dc VFED.... ......ID 0,0-1080,1716 #7f0901c9 app:id/expandableListView_search}, adapter:com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter@305b96e5, layout:android.support.v7.widget.LinearLayoutManager@191735ba, context:com.loyo.oa.v2.project.activity.ProjectSearchOrPickerActivity@52be4b6
        at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:810)
        at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
        at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7984)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7961)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7949)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1570)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
        at android.view.View.layout(View.java:15734)
        at android.view.ViewGroup.layout(ViewGroup.java:5196)

**Comment by af913337456** [comment]
是否使用了 1.5.9 版本？

**Comment by af913337456** [comment]
是否是动态添加头部，还是静态添加？

**Comment by stonebirds** [comment]
这个问题在1.6.0之中解决了吗？

**Comment by stonebirds** [comment]
> 是否使用了 1.5.9 版本？

这个在1.6.0之中有修复吗？？？，我们现在的bugly上之前的旧代码也一直在摆这个错误，如果修复的话，我们就可以升级一下处理，否则还得替换
