### ISSUE TITLE
可以支持androidx吗

### ISSUE THREAD

**Issue by wtwt91** [XRecyclerView/XRecyclerView#373]
如题，可以支持androidx吗

**Comment by af913337456** [comment]
可以

**Comment by hardlove** [comment]
Caused by: android.view.InflateException: Binary XML file line #40: Binary XML file line #40: Error inflating class com.zhouyou.recyclerview.XRecyclerView
     Caused by: android.view.InflateException: Binary XML file line #40: Error inflating class com.zhouyou.recyclerview.XRecyclerView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)

不支持AndroidX吧
