### ISSUE TITLE
在已经加入adapter的情况下，setLoadingMoreEnabled为false之后是不是得notify一下？

### ISSUE THREAD

**Issue by dy1023348109** [XRecyclerView/XRecyclerView#398]
在已经加入adapter的情况下，setLoadingMoreEnabled为false之后是不是得notify一下？
报了这个bug 每次的position 都是item数量+1. 看了下源码 是不是在没有更多数据时，setLoadingMoreEnabled为false之后notify一下就可以解决？
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{dddcd60 position=8 id=-1, oldPos=-1, pLpos:-1 no parent} com.jcodecraeer.xrecyclerview.XRecyclerView{529c22e VFED..... ........ 0,0-720,1218 #7f09054a app:id/a8u}, adapter:com.jcodecraeer.xrecyclerview.XRecyclerView$d@76ec3eb, 
       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)

**Comment by Kevin1466** [comment]
> 在已经加入adapter的情况下，setLoadingMoreEnabled为false之后是不是得notify一下？
> 报了这个bug 每次的position 都是item数量+1. 看了下源码 是不是在没有更多数据时，setLoadingMoreEnabled为false之后notify一下就可以解决？
> Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{dddcd60 position=8 id=-1, oldPos=-1, pLpos:-1 no parent} com.jcodecraeer.xrecyclerview.XRecyclerView{529c22e VFED..... ........ 0,0-720,1218 #7f09054a app:id/a8u}, adapter:com.jcodecraeer.xrecyclerview.XRecyclerView$d@76ec3eb,
> at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)

解决了吗？

**Comment by dy1023348109** [comment]
> > 在已经加入adapter的情况下，setLoadingMoreEnabled为false之后是不是得notify一下？
> > 报了这个bug 每次的position 都是item数量+1. 看了下源码 是不是在没有更多数据时，setLoadingMoreEnabled为false之后notify一下就可以解决？
> > Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{dddcd60 position=8 id=-1, oldPos=-1, pLpos:-1 no parent} com.jcodecraeer.xrecyclerview.XRecyclerView{529c22e VFED..... ........ 0,0-720,1218 #7f09054a app:id/a8u}, adapter:com.jcodecraeer.xrecyclerview.XRecyclerView$d@76ec3eb,
> > at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
> 
> 解决了吗？

好了，就是在这个setLoadingMoreEnable之后notify一下就行，setLoadingMoreEnabled相当于改变了adapter的数据。

**Comment by Kevin1466** [comment]
> > > 在已经加入adapter的情况下，setLoadingMoreEnabled为false之后是不是得notify一下？
> > > 报了这个bug 每次的position 都是item数量+1. 看了下源码 是不是在没有更多数据时，setLoadingMoreEnabled为false之后notify一下就可以解决？
> > > Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{dddcd60 position=8 id=-1, oldPos=-1, pLpos:-1 no parent} com.jcodecraeer.xrecyclerview.XRecyclerView{529c22e VFED..... ........ 0,0-720,1218 #7f09054a app:id/a8u}, adapter:com.jcodecraeer.xrecyclerview.XRecyclerView$d@76ec3eb,
> > > at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
> > 
> > 
> > 解决了吗？
> 
> 好了，就是在这个setLoadingMoreEnable之后notify一下就行，setLoadingMoreEnabled相当于改变了adapter的数据。

你这个bug是必现的吗？为你的读源码定位问题、分析问题的能力点赞！我也试一下你的解决方案，但是我的crash好像不是必现，不太好判断对我是否有效。

**Comment by Kevin1466** [comment]
> 在已经加入adapter的情况下，setLoadingMoreEnabled为false之后是不是得notify一下？
> 报了这个bug 每次的position 都是item数量+1. 看了下源码 是不是在没有更多数据时，setLoadingMoreEnabled为false之后notify一下就可以解决？
> Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{dddcd60 position=8 id=-1, oldPos=-1, pLpos:-1 no parent} com.jcodecraeer.xrecyclerview.XRecyclerView{529c22e VFED..... ........ 0,0-720,1218 #7f09054a app:id/a8u}, adapter:com.jcodecraeer.xrecyclerview.XRecyclerView$d@76ec3eb,
> at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)

https://stackoverflow.com/questions/35653439/recycler-view-inconsistency-detected-invalid-view-holder-adapter-positionviewh
这里有提出2个解决方案：
1. 继承LinearLayoutManager
2. The best solution is, clear the list every time before refresh RecyclerView.

第2个解决方案本质上和你的一样吗？
